### PR TITLE
Adding Jupyter Notebook Assignments

### PR DESCRIPTION
**Pull request by chaedri**
* Adding a description of  the Jupyter Notebook assignments to Logistics page.
* Changing links and description of Assignments and Homeworks 2A, 3ABC to Jupyter Notebooks

There's a description of how to use the assignment Github repository on the logistics page (download, unzip, launch etc.).

### CODE REVIEW

**Review by wenzeslaus — COMMENTED** [review]
Isn't a PDF better for a review in Moodle than HTML? Or is PDF harder to obtain (it may require LaTeX). If HTML works pretty well (embedded images) perhaps no reason for PDF if it is more complex to get.

**Comment by chaedri** [comment]
I think it's equally as easy to do PDFs. I was thinking HTML might be a better way to view notebooks, especially one's with the interactive maps. But, perhaps PDFs are easier to print/view/grade.

**Comment by wenzeslaus** [comment]
I didn't think about the interactive maps. Any opinion @hmitaso?

**Comment by hmitaso** [comment]
Caitlin, you can submit a html to moodle and try it out - I believe it should be OK but I have never had to deal with it - as long as it does not convert everything to pdf (as it does with docx files) it should be OK).
They can also store it on github or google drive and provide just a link with brief description in a pdf file.
Also, please keep the link to the original assignment as well  - see how I did the links for Assignment 1A.
(it is my experience that the old material does not get used in 99% of cases but it is good to have it around the first time the new material is used)

**Comment by chaedri** [comment]
I couldn't figure out how to test since I'm not a student in the course but I did some research and I think it will work. I also remember submitting Rmarkdown documents in Josh's class and other atypical file formats in Dr. Tateosian's class. 

I added the original file links back. They contain the answers to some of the questions but I can see it could be useful to have around for the first time around.

**Pull request merged**
